### ISSUE TITLE
Code and Datasets?

### ISSUE THREAD

**Issue by sisrfeng** [avijit9/awesome-computer-vision-in-sports#3]
Thank you for sharing!
Have you tried running any code of the papers and found more datasets (especially for badminton)?
I've read many papers in this topic, but only find useful code with TrackNetv1 and v2

**Comment by avijit9** [comment]
Unfortunately no. I didn't get time to track.

**Comment by avijit9** [comment]
@sisrfeng  feel free to add anything you find useful.
